[36m[2023-11-28 10:18:29 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-28 10:18:29 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-28 10:18:29 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-28 10:18:32 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-28 10:18:32 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 10:18:32 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:04:17 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-28 16:04:17 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-28 16:04:17 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-28 16:04:19 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-28 16:04:19 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:04:19 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:04:19 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-28 16:04:19 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-28 16:04:19 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-28 16:04:19 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-28 16:04:19 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-28 16:04:19 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-28 16:04:19 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-28 16:04:19 ERROR] [cli:278][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-28 16:04:19 DEBUG] [cli:279][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-28 16:07:43 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-28 16:07:43 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-28 16:07:43 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-28 16:07:44 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-28 16:07:44 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:07:44 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:07:44 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-28 16:07:44 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-28 16:07:44 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-28 16:07:44 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-28 16:07:44 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-28 16:07:44 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-28 16:07:44 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-28 16:30:17 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-28 16:30:17 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-28 16:30:17 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-28 16:30:18 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-28 16:30:18 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:30:18 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:30:18 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-28 16:30:18 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-28 16:30:18 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-28 16:30:18 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-28 16:30:18 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-28 16:30:18 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-28 16:30:18 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-28 16:30:18 ERROR] [cli:278][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-28 16:30:18 DEBUG] [cli:279][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-28 16:30:37 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-28 16:30:37 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-28 16:30:37 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-28 16:30:38 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-28 16:30:38 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:30:38 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:30:38 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-28 16:30:38 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-28 16:30:38 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-28 16:30:38 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-28 16:30:38 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-28 16:30:38 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-28 16:30:38 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-28 16:30:38 ERROR] [cli:278][39m could not find Python module '/processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-28 16:30:38 DEBUG] [cli:279][39m could not find Python module '/processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-28 16:32:50 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-28 16:32:50 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-28 16:32:50 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-28 16:32:51 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-28 16:32:51 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:32:51 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:32:51 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-28 16:32:51 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-28 16:32:51 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-28 16:32:51 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-28 16:32:51 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-28 16:32:51 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-28 16:32:51 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-28 16:35:27 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-28 16:35:27 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-28 16:35:27 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-28 16:35:29 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-28 16:35:29 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:35:29 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:35:29 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-28 16:35:29 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-28 16:35:29 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-28 16:35:29 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-28 16:35:29 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-28 16:35:29 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-28 16:35:29 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-28 16:35:29 ERROR] [cli:278][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-28 16:35:29 DEBUG] [cli:279][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-28 16:40:46 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-28 16:40:46 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-28 16:40:46 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-28 16:40:48 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-28 16:40:48 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:40:48 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:40:48 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-28 16:40:48 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-28 16:40:48 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-28 16:40:48 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-28 16:40:48 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-28 16:40:48 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-28 16:40:49 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-28 16:40:49 ERROR] [cli:278][39m a Python activity must have a function name
[36m[2023-11-28 16:40:49 DEBUG] [cli:279][39m a Python activity must have a function name
[36m[2023-11-28 16:44:46 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-28 16:44:46 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-28 16:44:46 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-28 16:44:47 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-28 16:44:47 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:44:48 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-28 16:44:48 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-28 16:44:48 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-28 16:44:48 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-28 16:44:48 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-28 16:44:48 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-28 16:44:48 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-28 16:44:49 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-28 16:44:49 ERROR] [cli:278][39m a Python activity must have a function name
[36m[2023-11-28 16:44:49 DEBUG] [cli:279][39m a Python activity must have a function name
[36m[2023-11-29 09:25:55 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:25:55 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:25:55 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:25:56 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:25:56 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:25:56 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:25:56 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:25:56 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:25:56 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:25:56 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:25:56 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:25:56 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:25:56 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-29 09:25:56 ERROR] [cli:278][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-29 09:25:56 DEBUG] [cli:279][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-29 09:27:53 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:27:53 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:27:53 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:27:54 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:27:54 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:27:54 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:27:54 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:27:54 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:27:54 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:27:54 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:27:54 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:27:54 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:27:55 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-29 09:27:55 ERROR] [cli:278][39m a Python activity must have a function name
[36m[2023-11-29 09:27:55 DEBUG] [cli:279][39m a Python activity must have a function name
[36m[2023-11-29 09:29:02 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:29:02 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:29:02 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:29:03 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:29:03 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:29:03 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:29:03 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:29:03 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:29:03 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:29:03 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:29:03 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:29:03 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:29:04 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-29 09:29:04 ERROR] [cli:278][39m a Python activity must have a function name
[36m[2023-11-29 09:29:04 DEBUG] [cli:279][39m a Python activity must have a function name
[36m[2023-11-29 09:31:17 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:31:17 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:31:17 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:31:19 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:31:19 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:31:19 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:31:19 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:31:19 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:31:19 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:31:19 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:31:19 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:31:19 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:31:19 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-29 09:31:19 ERROR] [cli:278][39m a Python activity must have a function name
[36m[2023-11-29 09:31:19 DEBUG] [cli:279][39m a Python activity must have a function name
[36m[2023-11-29 09:31:36 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:31:36 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:31:36 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:31:37 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:31:37 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:31:37 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:31:37 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:31:37 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:31:37 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:31:37 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:31:37 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:31:37 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:31:38 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-29 09:31:38 ERROR] [cli:278][39m a process activity must have a path
[36m[2023-11-29 09:31:38 DEBUG] [cli:279][39m a process activity must have a path
[36m[2023-11-29 09:33:10 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:33:10 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:33:10 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:33:11 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:33:11 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:33:11 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:33:11 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:33:11 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:33:11 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:33:11 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:33:11 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:33:11 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:33:11 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-29 09:33:11 ERROR] [cli:278][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-29 09:33:11 DEBUG] [cli:279][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-29 09:43:44 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:43:44 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:43:44 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:43:45 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:43:45 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:43:45 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:43:45 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:43:45 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:43:45 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:43:45 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:43:45 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:43:45 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:43:45 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-29 09:43:45 ERROR] [cli:278][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-29 09:43:45 DEBUG] [cli:279][39m could not find Python module 'processMonitoring' in activity 'the-cinema-booking-service-must-be-running'
[36m[2023-11-29 09:47:29 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:47:29 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:47:29 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:47:30 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:47:30 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:47:30 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:47:30 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:47:30 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:47:30 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:47:30 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:47:30 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:47:30 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:47:36 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-11-29 09:47:36 ERROR] [cli:278][39m empty activity is no activity
[36m[2023-11-29 09:47:36 DEBUG] [cli:279][39m empty activity is no activity
[36m[2023-11-29 09:48:00 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:48:00 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:48:00 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:48:01 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:48:01 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:48:01 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:48:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:48:01 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:48:01 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:48:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:48:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:48:01 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 09:48:07 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 09:48:07 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 09:48:07 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 09:48:07 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:48:07 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-11-29 09:48:07 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:48:07 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:48:07 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:48:07 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-29 09:48:07 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-11-29 09:48:07 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-11-29 09:48:07 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 09:48:07 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 09:48:07 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 09:48:07 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 09:48:07 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 09:48:07 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 09:48:07 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 09:48:07 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 09:48:07 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 09:48:07 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 09:48:07 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-29 09:48:07 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 09:48:07 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-29 09:48:07 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 09:48:07 CRITICAL] [run:579][39m Steady state probe 'the-cinema-booking-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-29 09:48:07 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 09:48:07 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 09:48:07 INFO] [rollback:32][39m No declared rollbacks, let's move on.
[36m[2023-11-29 09:48:07 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 09:48:07 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-29 09:48:07 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 09:48:07 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 09:48:07 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 09:50:09 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:50:09 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:50:09 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:50:11 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:50:11 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:50:11 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:50:11 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:50:11 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:50:11 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:50:11 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:50:11 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:50:11 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 09:50:16 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 09:50:16 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 09:50:16 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 09:50:16 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:50:16 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-11-29 09:50:16 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:50:16 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:50:16 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:50:16 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-29 09:50:16 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-11-29 09:50:16 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-11-29 09:50:16 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 09:50:16 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 09:50:16 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 09:50:16 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 09:50:16 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 09:50:16 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 09:50:16 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 09:50:16 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 09:50:16 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 09:50:16 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 09:50:16 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-29 09:50:16 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 09:50:16 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-29 09:50:16 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 09:50:16 CRITICAL] [run:579][39m Steady state probe 'the-cinema-booking-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-29 09:50:16 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 09:50:16 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 09:50:16 INFO] [rollback:32][39m No declared rollbacks, let's move on.
[36m[2023-11-29 09:50:16 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 09:50:16 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-29 09:50:16 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 09:50:16 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 09:50:16 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 09:51:00 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:51:00 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:51:00 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:51:01 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:51:01 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:51:01 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:51:01 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:51:01 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:51:01 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:51:01 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:51:01 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:51:01 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 09:51:07 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 09:51:07 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 09:51:07 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 09:51:07 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:51:07 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-11-29 09:51:07 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:51:07 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:51:07 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:51:07 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-29 09:51:07 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-11-29 09:51:07 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-11-29 09:51:07 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 09:51:07 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 09:51:07 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 09:51:07 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 09:51:07 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 09:51:07 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 09:51:07 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 09:51:07 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 09:51:07 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 09:51:07 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 09:51:07 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-29 09:51:07 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 09:51:07 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-29 09:51:07 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 09:51:07 CRITICAL] [run:579][39m Steady state probe 'the-cinema-booking-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-29 09:51:07 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 09:51:07 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 09:51:07 INFO] [rollback:32][39m No declared rollbacks, let's move on.
[36m[2023-11-29 09:51:07 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 09:51:07 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-29 09:51:07 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 09:51:07 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 09:51:07 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 09:53:33 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:53:33 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:53:33 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:53:34 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:53:34 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:53:34 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:53:34 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:53:34 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:53:34 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:53:34 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:53:34 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:53:34 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 09:53:35 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 09:53:35 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 09:53:35 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 09:53:35 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:53:35 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-11-29 09:53:35 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:53:35 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:53:35 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:53:35 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-29 09:53:35 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-11-29 09:53:35 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-11-29 09:53:35 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 09:53:35 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 09:53:35 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 09:53:35 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 09:53:35 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 09:53:35 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 09:53:35 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 09:53:35 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 09:53:35 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 09:53:35 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 09:53:35 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 09:53:35 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 09:53:35 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-11-29 09:53:35 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-29 09:53:35 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-29 09:53:35 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-29 09:53:35 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 09:53:35 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 09:53:35 INFO] [activity:215][39m Action: kill-cinema-booking-Service
[36m[2023-11-29 09:53:35 DEBUG] [python:33][39m Activity 'kill-cinema-booking-Service' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processKilling.py'
[36m[2023-11-29 09:53:35 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 09:53:35 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 09:53:35 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 09:53:35 INFO] [activity:215][39m Probe: measure-duration-until-cinema-booking-Service-is-available-again
[36m[2023-11-29 09:53:35 DEBUG] [python:33][39m Activity 'measure-duration-until-cinema-booking-Service-is-available-again' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 09:53:46 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-11-29 09:53:46 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 09:53:46 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 09:53:46 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-29 09:53:46 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 09:53:46 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 09:53:46 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 09:53:46 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 09:53:46 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 09:53:46 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-29 09:53:46 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 09:53:46 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-29 09:53:46 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 09:53:46 CRITICAL] [run:615][39m Steady state probe 'the-cinema-booking-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-29 09:53:46 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 09:53:46 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 09:53:46 INFO] [rollback:32][39m No declared rollbacks, let's move on.
[36m[2023-11-29 09:53:46 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 09:53:46 INFO] [run:515][39m Experiment ended with status: deviated
[32m[2023-11-29 09:53:46 INFO] [run:517][39m The steady-state has deviated, a weakness may have been discovered
[36m[2023-11-29 09:53:46 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 09:53:46 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 09:53:46 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 09:55:25 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 09:55:25 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 09:55:25 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 09:55:26 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 09:55:26 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:55:26 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 09:55:26 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:55:26 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 09:55:26 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 09:55:26 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:55:26 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:55:26 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 09:55:31 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 09:55:31 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 09:55:31 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 09:55:31 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 09:55:31 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-11-29 09:55:31 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 09:55:31 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 09:55:31 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 09:55:31 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-29 09:55:31 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-11-29 09:55:31 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-11-29 09:55:31 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 09:55:31 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 09:55:31 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 09:55:31 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 09:55:31 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 09:55:31 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 09:55:31 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 09:55:31 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 09:55:31 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 09:55:31 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 09:55:32 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-29 09:55:32 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 09:55:32 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-29 09:55:32 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 09:55:32 CRITICAL] [run:579][39m Steady state probe 'the-cinema-booking-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-29 09:55:32 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 09:55:32 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 09:55:32 INFO] [rollback:32][39m No declared rollbacks, let's move on.
[36m[2023-11-29 09:55:32 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 09:55:32 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-29 09:55:32 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 09:55:32 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 09:55:32 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 10:18:40 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 10:18:40 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 10:18:40 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 10:18:42 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 10:18:42 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 10:18:42 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 10:18:42 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 10:18:42 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 10:18:42 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 10:18:42 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 10:18:42 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 10:18:42 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 10:18:47 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 10:20:54 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 10:20:54 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 10:20:54 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 10:20:55 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 10:20:55 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 10:20:55 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 10:20:55 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 10:20:55 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 10:20:55 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 10:20:55 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 10:20:55 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 10:20:55 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 10:21:00 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 10:21:00 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 10:21:00 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 10:21:00 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 10:21:00 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-11-29 10:21:00 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 10:21:00 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 10:21:00 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 10:21:00 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-29 10:21:00 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-11-29 10:21:00 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-11-29 10:21:00 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 10:21:00 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 10:21:00 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 10:21:00 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 10:21:00 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 10:21:00 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 10:21:00 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 10:21:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:21:00 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 10:21:00 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 10:21:01 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-29 10:21:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:21:01 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-29 10:21:01 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 10:21:01 CRITICAL] [run:579][39m Steady state probe 'the-cinema-booking-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-29 10:21:01 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 10:21:01 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 10:21:01 INFO] [rollback:35][39m Rollback: start-process-if-not-already-restarted
[36m[2023-11-29 10:21:01 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:21:01 INFO] [activity:215][39m Action: start-process-if-not-already-restarted
[36m[2023-11-29 10:21:01 DEBUG] [python:33][39m Activity 'start-process-if-not-already-restarted' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processStarting.py'
[36m[2023-11-29 10:21:45 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-11-29 10:21:45 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:21:45 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 10:21:45 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-11-29 10:21:45 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 10:21:45 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 10:21:45 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 10:22:06 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 10:22:06 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 10:22:06 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 10:22:07 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 10:22:07 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 10:22:07 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 10:22:07 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 10:22:07 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 10:22:07 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 10:22:07 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 10:22:07 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 10:22:07 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 10:22:07 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 10:22:07 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 10:22:07 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 10:22:07 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 10:22:07 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-11-29 10:22:07 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 10:22:07 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 10:22:07 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 10:22:07 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-29 10:22:07 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-11-29 10:22:07 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-11-29 10:22:07 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 10:22:07 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 10:22:07 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 10:22:07 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 10:22:07 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 10:22:07 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 10:22:07 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 10:22:07 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:22:07 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 10:22:07 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 10:22:08 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 10:22:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:22:08 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-11-29 10:22:08 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-29 10:22:08 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-29 10:22:08 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-29 10:22:08 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 10:22:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:22:08 INFO] [activity:215][39m Action: kill-cinema-booking-Service
[36m[2023-11-29 10:22:08 DEBUG] [python:33][39m Activity 'kill-cinema-booking-Service' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processKilling.py'
[36m[2023-11-29 10:22:08 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 10:22:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:22:08 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:22:08 INFO] [activity:215][39m Probe: measure-duration-until-cinema-booking-Service-is-available-again
[36m[2023-11-29 10:22:08 DEBUG] [python:33][39m Activity 'measure-duration-until-cinema-booking-Service-is-available-again' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 10:22:18 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-11-29 10:22:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:22:18 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 10:22:18 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-29 10:22:18 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 10:22:18 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 10:22:18 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:22:18 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 10:22:18 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 10:22:19 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-29 10:22:19 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:22:19 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-29 10:22:19 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 10:22:19 CRITICAL] [run:615][39m Steady state probe 'the-cinema-booking-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-29 10:22:19 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 10:22:19 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 10:22:19 INFO] [rollback:35][39m Rollback: start-process
[36m[2023-11-29 10:22:19 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:22:19 INFO] [activity:215][39m Action: start-process
[36m[2023-11-29 10:22:19 DEBUG] [python:33][39m Activity 'start-process' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processStarting.py'
[36m[2023-11-29 10:32:02 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:32:02 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[33m[2023-11-29 10:32:02 WARNING] [run:762][39m Received an exit signal.Terminating now without running the remaining rollbacks.
[32m[2023-11-29 10:32:02 INFO] [run:515][39m Experiment ended with status: deviated
[32m[2023-11-29 10:32:02 INFO] [run:517][39m The steady-state has deviated, a weakness may have been discovered
[36m[2023-11-29 10:32:02 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 10:32:02 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-11-29 10:32:02 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 10:34:12 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 10:34:12 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-11-29 10:34:12 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-11-29 10:34:14 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-11-29 10:34:14 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 10:34:14 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-11-29 10:34:14 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-11-29 10:34:14 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 10:34:14 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 10:34:14 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-11-29 10:34:14 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-11-29 10:34:14 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-11-29 10:34:14 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-11-29 10:34:14 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 10:34:14 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-11-29 10:34:14 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-11-29 10:34:14 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-11-29 10:34:14 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-11-29 10:34:14 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-11-29 10:34:14 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-11-29 10:34:14 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-11-29 10:34:14 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-11-29 10:34:14 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-11-29 10:34:14 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-11-29 10:34:14 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-11-29 10:34:14 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:34:14 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 10:34:14 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 10:34:14 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:34:14 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-11-29 10:34:14 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-11-29 10:34:14 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:34:14 INFO] [activity:215][39m Action: kill-cinema-booking-Service
[36m[2023-11-29 10:34:14 DEBUG] [python:33][39m Activity 'kill-cinema-booking-Service' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processKilling.py'
[36m[2023-11-29 10:34:14 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:34:14 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:34:14 INFO] [activity:215][39m Probe: measure-duration-until-cinema-booking-Service-is-available-again
[36m[2023-11-29 10:34:14 DEBUG] [python:33][39m Activity 'measure-duration-until-cinema-booking-Service-is-available-again' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 10:34:24 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-11-29 10:34:24 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:34:24 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-11-29 10:34:24 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-11-29 10:34:24 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-11-29 10:34:24 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-11-29 10:34:24 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:34:24 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-11-29 10:34:24 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-11-29 10:34:25 DEBUG] [activity:237][39m   => succeeded with 'False'
[36m[2023-11-29 10:34:25 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-11-29 10:34:25 DEBUG] [hypothesis:228][39m allowed tolerance is True
[36m[2023-11-29 10:34:25 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[31m[2023-11-29 10:34:25 CRITICAL] [run:615][39m Steady state probe 'the-cinema-booking-service-must-be-running' is not in the given tolerance so failing this experiment
[32m[2023-11-29 10:34:25 INFO] [run:966][39m Let's rollback...
[36m[2023-11-29 10:34:25 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-11-29 10:34:25 INFO] [rollback:35][39m Rollback: start-process
[36m[2023-11-29 10:34:25 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-11-29 10:34:25 INFO] [activity:215][39m Action: start-process
[36m[2023-11-29 10:34:25 DEBUG] [python:33][39m Activity 'start-process' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processStarting.py'
[36m[2023-11-29 10:50:33 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 10:50:33 DEBUG] [cli:115][39m Running command 'report'
[36m[2023-11-29 10:50:33 DEBUG] [cli:119][39m Using settings file '/.chaostoolkit/settings.yaml'
[33m[2023-11-29 10:50:34 WARNING] [check:33][39m 
    There is a new version (1.16.0) of the chaostoolkit available.
    You may upgrade by typing:
    
    $ pip install -U chaostoolkit
    
    Please review changes at https://github.com/chaostoolkit/chaostoolkit/blob/master/CHANGELOG.md
    
[36m[2023-11-29 10:50:34 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 10:50:34 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-11-29 10:56:38 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-11-29 10:56:38 DEBUG] [cli:115][39m Running command 'report'
[36m[2023-11-29 10:56:38 DEBUG] [cli:119][39m Using settings file '/.chaostoolkit/settings.yaml'
[33m[2023-11-29 10:56:39 WARNING] [check:33][39m 
    There is a new version (1.16.0) of the chaostoolkit available.
    You may upgrade by typing:
    
    $ pip install -U chaostoolkit
    
    Please review changes at https://github.com/chaostoolkit/chaostoolkit/blob/master/CHANGELOG.md
    
[36m[2023-11-29 10:56:39 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-11-29 10:56:39 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-12-04 15:21:44 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-12-04 15:21:44 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-12-04 15:21:44 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-12-04 15:21:45 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-12-04 15:21:45 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-04 15:21:45 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-04 15:21:45 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-04 15:21:45 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-12-04 15:21:45 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-12-04 15:21:45 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-04 15:21:45 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-04 15:21:45 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-04 15:21:46 DEBUG] [caching:42][39m Clearing activities cache
[31m[2023-12-04 15:21:46 ERROR] [cli:278][39m required argument 'checking_interval_sec' is missing from activity 'get_duration_until_process_started'
[36m[2023-12-04 15:21:46 DEBUG] [cli:279][39m required argument 'checking_interval_sec' is missing from activity 'get_duration_until_process_started'
[36m[2023-12-04 15:22:30 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-12-04 15:22:30 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-12-04 15:22:30 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-12-04 15:22:31 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-12-04 15:22:31 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-04 15:22:31 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-04 15:22:31 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-04 15:22:31 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-12-04 15:22:31 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-12-04 15:22:31 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-04 15:22:31 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-04 15:22:31 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-12-04 15:22:36 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-12-04 15:22:36 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-04 15:22:36 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-12-04 15:22:36 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-04 15:22:36 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-12-04 15:22:36 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-04 15:22:36 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-04 15:22:36 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-04 15:22:36 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-12-04 15:22:36 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-12-04 15:22:36 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-12-04 15:22:36 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-12-04 15:22:36 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-12-04 15:22:36 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-12-04 15:22:36 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-04 15:22:36 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-12-04 15:22:36 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-12-04 15:22:36 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-04 15:22:36 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-04 15:22:36 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-12-04 15:22:36 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-04 15:22:36 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-04 15:22:36 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-04 15:22:36 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-12-04 15:22:36 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-12-04 15:22:36 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-12-04 15:22:36 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-12-04 15:22:36 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-12-04 15:22:36 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-04 15:22:36 INFO] [activity:215][39m Action: kill-cinema-booking-Service
[36m[2023-12-04 15:22:36 DEBUG] [python:33][39m Activity 'kill-cinema-booking-Service' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processKilling.py'
[36m[2023-12-04 15:22:37 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-04 15:22:37 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-04 15:22:37 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-04 15:22:37 INFO] [activity:215][39m Probe: measure-duration-until-cinema-booking-Service-is-available-again
[36m[2023-12-04 15:22:37 DEBUG] [python:33][39m Activity 'measure-duration-until-cinema-booking-Service-is-available-again' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-04 15:22:47 DEBUG] [activity:237][39m   => succeeded with '0:00:09.929942'
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-12-04 15:22:47 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-12-04 15:22:47 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-04 15:22:47 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-12-04 15:22:47 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-04 15:22:47 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-04 15:22:47 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-12-04 15:22:47 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-12-04 15:22:47 INFO] [run:966][39m Let's rollback...
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-12-04 15:22:47 INFO] [rollback:35][39m Rollback: start-process
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-04 15:22:47 INFO] [activity:215][39m Action: start-process
[36m[2023-12-04 15:22:47 DEBUG] [python:33][39m Activity 'start-process' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processStarting.py'
[36m[2023-12-04 15:22:47 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-12-04 15:22:47 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-12-04 15:22:47 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-04 15:22:47 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-12-04 15:22:47 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-04 15:46:50 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-12-04 15:46:50 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-12-04 15:46:50 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-12-04 15:46:51 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-12-04 15:46:51 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-04 15:46:51 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-04 15:46:51 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-04 15:46:51 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-12-04 15:46:51 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-12-04 15:46:51 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-04 15:46:51 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-04 15:46:51 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-12-04 15:46:52 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-12-04 15:46:52 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-04 15:46:52 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-12-04 15:46:52 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-04 15:46:52 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-12-04 15:46:52 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-04 15:46:52 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-04 15:46:52 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-04 15:46:52 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-12-04 15:46:52 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-12-04 15:46:52 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-12-04 15:46:52 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-12-04 15:46:52 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-12-04 15:46:52 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-12-04 15:46:52 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-04 15:46:52 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-12-04 15:46:52 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-12-04 15:46:52 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-04 15:46:52 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-04 15:46:52 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-12-04 15:46:52 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-04 15:46:52 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-04 15:46:52 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-04 15:46:52 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-12-04 15:46:52 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-12-04 15:46:52 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-12-04 15:46:52 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-12-04 15:46:52 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-12-04 15:46:52 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-04 15:46:52 INFO] [activity:215][39m Action: kill-cinema-booking-Service
[36m[2023-12-04 15:46:52 DEBUG] [python:33][39m Activity 'kill-cinema-booking-Service' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processKilling.py'
[36m[2023-12-04 15:46:53 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-04 15:46:53 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-04 15:46:53 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-04 15:46:53 INFO] [activity:215][39m Probe: measure-duration-until-cinema-booking-Service-is-available-again
[36m[2023-12-04 15:46:53 DEBUG] [python:33][39m Activity 'measure-duration-until-cinema-booking-Service-is-available-again' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-04 15:47:00 DEBUG] [activity:237][39m   => succeeded with '6.658325'
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-12-04 15:47:00 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-12-04 15:47:00 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-04 15:47:00 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-12-04 15:47:00 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-04 15:47:00 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-04 15:47:00 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-12-04 15:47:00 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-12-04 15:47:00 INFO] [run:966][39m Let's rollback...
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-12-04 15:47:00 INFO] [rollback:35][39m Rollback: start-process
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-04 15:47:00 INFO] [activity:215][39m Action: start-process
[36m[2023-12-04 15:47:00 DEBUG] [python:33][39m Activity 'start-process' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processStarting.py'
[36m[2023-12-04 15:47:00 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-12-04 15:47:00 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-12-04 15:47:00 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-04 15:47:00 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-12-04 15:47:00 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-05 08:38:48 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-12-05 08:38:48 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-12-05 08:38:48 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-12-05 08:38:49 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-12-05 08:38:49 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-05 08:38:49 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-05 08:38:49 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-05 08:38:49 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-12-05 08:38:49 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-12-05 08:38:49 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-05 08:38:49 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-05 08:38:49 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-05 08:38:57 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-05 08:40:52 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-12-05 08:40:52 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-12-05 08:40:52 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-12-05 08:40:53 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-12-05 08:40:53 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-05 08:40:53 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-05 08:40:53 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-05 08:40:53 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-12-05 08:40:53 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-12-05 08:40:53 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-05 08:40:53 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-05 08:40:53 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-12-05 08:40:53 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-12-05 08:40:53 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-05 08:40:53 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-12-05 08:40:53 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-05 08:40:53 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-12-05 08:40:53 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-05 08:40:53 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-05 08:40:53 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-05 08:40:53 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-12-05 08:40:53 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-12-05 08:40:53 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-12-05 08:40:53 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-12-05 08:40:53 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-12-05 08:40:53 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-12-05 08:40:53 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-05 08:40:53 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-12-05 08:40:53 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-12-05 08:40:53 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-05 08:40:53 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-05 08:40:53 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-12-05 08:40:53 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-05 08:40:54 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-05 08:40:54 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-05 08:40:54 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-12-05 08:40:54 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-12-05 08:40:54 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-12-05 08:40:54 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-12-05 08:40:54 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-12-05 08:40:54 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-05 08:40:54 INFO] [activity:215][39m Action: kill-cinema-booking-Service
[36m[2023-12-05 08:40:54 DEBUG] [python:33][39m Activity 'kill-cinema-booking-Service' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processKilling.py'
[36m[2023-12-05 08:40:54 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-05 08:40:54 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-05 08:40:54 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-05 08:40:54 INFO] [activity:215][39m Probe: measure-duration-until-cinema-booking-Service-is-available-again
[36m[2023-12-05 08:40:54 DEBUG] [python:33][39m Activity 'measure-duration-until-cinema-booking-Service-is-available-again' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-05 08:40:59 DEBUG] [activity:237][39m   => succeeded with '5.153853'
[36m[2023-12-05 08:40:59 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-05 08:40:59 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-12-05 08:40:59 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-12-05 08:40:59 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-12-05 08:40:59 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-05 08:40:59 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-05 08:40:59 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-12-05 08:40:59 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-05 08:41:00 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-05 08:41:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-05 08:41:00 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-12-05 08:41:00 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-12-05 08:41:00 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-12-05 08:41:00 INFO] [run:966][39m Let's rollback...
[36m[2023-12-05 08:41:00 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-12-05 08:41:00 INFO] [rollback:35][39m Rollback: start-process
[36m[2023-12-05 08:41:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-05 08:41:00 INFO] [activity:215][39m Action: start-process
[36m[2023-12-05 08:41:00 DEBUG] [python:33][39m Activity 'start-process' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processStarting.py'
[36m[2023-12-05 08:41:00 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-12-05 08:41:00 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-05 08:41:00 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-12-05 08:41:00 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-12-05 08:41:00 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-05 08:41:00 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-12-05 08:41:00 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-05 08:49:15 DEBUG] [cli:114][39m ###############################################################################
[36m[2023-12-05 08:49:15 DEBUG] [cli:115][39m Running command 'run'
[36m[2023-12-05 08:49:15 DEBUG] [cli:119][39m Using settings file 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'
[36m[2023-12-05 08:49:16 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at 'C:\Users\HenningMöllers\.chaostoolkit\settings.yaml'.
[36m[2023-12-05 08:49:16 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-05 08:49:16 DEBUG] [__init__:445][39m No controls to apply on 'loader'
[36m[2023-12-05 08:49:16 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-05 08:49:16 DEBUG] [caching:35][39m Cached 3 activities
[32m[2023-12-05 08:49:16 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2023-12-05 08:49:16 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-05 08:49:16 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-05 08:49:16 DEBUG] [secret:103][39m Done loading secrets
[32m[2023-12-05 08:49:20 INFO] [experiment:109][39m Experiment looks valid
[36m[2023-12-05 08:49:20 DEBUG] [caching:42][39m Clearing activities cache
[36m[2023-12-05 08:49:20 DEBUG] [cli:314][39m Runtime strategies: hypothesis - default / rollbacks - default
[36m[2023-12-05 08:49:20 DEBUG] [caching:24][39m Building activity cache...
[36m[2023-12-05 08:49:20 DEBUG] [caching:35][39m Cached 3 activities
[36m[2023-12-05 08:49:20 DEBUG] [configuration:63][39m Loading configuration...
[36m[2023-12-05 08:49:20 DEBUG] [secret:78][39m Loading secrets...
[36m[2023-12-05 08:49:20 DEBUG] [secret:103][39m Done loading secrets
[36m[2023-12-05 08:49:20 DEBUG] [configuration:160][39m Loading dynamic configuration...
[36m[2023-12-05 08:49:20 DEBUG] [exit:89][39m System 'Windows-10-10.0.22631-SP0' does not expose SIGUSR signals
[32m[2023-12-05 08:49:20 INFO] [run:369][39m Running experiment: CinemaBookingUnaivalabilty
[36m[2023-12-05 08:49:20 DEBUG] [__init__:59][39m Initializing controls
[32m[2023-12-05 08:49:20 INFO] [run:396][39m Steady-state strategy: default
[32m[2023-12-05 08:49:20 INFO] [run:400][39m Rollbacks strategy: default
[36m[2023-12-05 08:49:20 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-05 08:49:20 DEBUG] [run:563][39m Running steady-state hypothesis before the method
[32m[2023-12-05 08:49:20 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-12-05 08:49:20 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-05 08:49:20 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-05 08:49:20 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-12-05 08:49:20 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-05 08:49:21 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-05 08:49:21 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-05 08:49:21 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-12-05 08:49:21 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-12-05 08:49:21 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-12-05 08:49:21 INFO] [run:677][39m Playing your experiment's method now...
[36m[2023-12-05 08:49:21 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-12-05 08:49:21 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-05 08:49:21 INFO] [activity:215][39m Action: kill-cinema-booking-Service
[36m[2023-12-05 08:49:21 DEBUG] [python:33][39m Activity 'kill-cinema-booking-Service' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processKilling.py'
[36m[2023-12-05 08:49:21 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-05 08:49:21 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-05 08:49:21 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-05 08:49:21 INFO] [activity:215][39m Probe: measure-duration-until-cinema-booking-Service-is-available-again
[36m[2023-12-05 08:49:21 DEBUG] [python:33][39m Activity 'measure-duration-until-cinema-booking-Service-is-available-again' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-05 08:49:29 DEBUG] [activity:237][39m   => succeeded with '7.432702'
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'method'
[36m[2023-12-05 08:49:29 DEBUG] [run:599][39m Running steady-state hypothesis after the method
[32m[2023-12-05 08:49:29 INFO] [hypothesis:186][39m Steady state hypothesis: Application responds
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-05 08:49:29 INFO] [activity:215][39m Probe: the-cinema-booking-service-must-be-running
[36m[2023-12-05 08:49:29 DEBUG] [python:33][39m Activity 'the-cinema-booking-service-must-be-running' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processMonitoring.py'
[36m[2023-12-05 08:49:29 DEBUG] [activity:237][39m   => succeeded with 'True'
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-05 08:49:29 DEBUG] [hypothesis:228][39m allowed tolerance is True
[32m[2023-12-05 08:49:29 INFO] [hypothesis:238][39m Steady state hypothesis is met!
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'hypothesis'
[32m[2023-12-05 08:49:29 INFO] [run:966][39m Let's rollback...
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-12-05 08:49:29 INFO] [rollback:35][39m Rollback: start-process
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[32m[2023-12-05 08:49:29 INFO] [activity:215][39m Action: start-process
[36m[2023-12-05 08:49:29 DEBUG] [python:33][39m Activity 'start-process' loaded from 'C:\Users\HenningMöllers\IdeaProjects\Dqualizer Resilienz Manuelle Uebersetzung\src\ctk\python\processStarting.py'
[36m[2023-12-05 08:49:29 DEBUG] [activity:239][39m   => succeeded without any result value
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'activity'
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'rollback'
[32m[2023-12-05 08:49:29 INFO] [run:515][39m Experiment ended with status: completed
[36m[2023-12-05 08:49:29 DEBUG] [__init__:445][39m No controls to apply on 'experiment'
[36m[2023-12-05 08:49:29 DEBUG] [__init__:98][39m Cleaning up controls
[36m[2023-12-05 08:49:29 DEBUG] [caching:42][39m Clearing activities cache
